### ISSUE TITLE
hi.

### ISSUE THREAD

**Issue by mzaboss** [Grivel-l/mySnapchatApi#1]
hello, kindly can i have your skype?

i need to talk to you regarding your API.

add me in skype: mzaboss

thank you.

**Comment by Grivel-l** [comment]
Hello,

Sure, I added you.

**Comment by rioisntfat** [comment]
hello, i just learned what node.js is today so i could implement your API. so im not experienced and dont understand much. but what i think im supposed to do is make a API call, but i was just wondering what i should have as the host.

**Comment by Grivel-l** [comment]
Hi, this is a very old project. The code is really dirty. But you should be able to run the project by:
- creating a SQL database and importing the sql file
- modifying the `user`, `password` and `database` value in each file of `models` folder
- Launch the server by running `node server.js`
When this is done you will be able to make your api call by following the doc on the homepage

**Comment by rioisntfat** [comment]
thanks, would i use node.js to create the database

**Comment by Grivel-l** [comment]
You have to use a database management system, use your search engine to learn how to do
